# 2:Linear Algebra

### The first Station --- Linear Algebra
Welcome! Please feel free to take a seat.  

In this section, we will introduce some basic information about linear algebra. 
 
First, we have to admit that, all quantum computing are base on matrix, so matrix is absolute the most important things in quantum computing, we have to understand what is matrix first.  

Second, we will introduce some notations and algorithms which will be used frequently in our later main body of quantum computing.  

So sharpening the knife does not make you miss the woodwork, let's begin our adventure together.


#### *2.1 Vector*
Before we step into matrix, the biggest problem we have to face is------What makes up matrix?

Some of you may say, you must be joking, all of us knows that numbers makes up matrix.
  
Woooo, take it easy, indeed numbers makes up matrix, that's true, but please think deeper, what if we divide the matrix into parts? You may already know the answer, a small matrix, that's right! You now warm up. But what if we divide it by rows and columns?  

Yeah, you are right, the vectors! Congrats!

Let's start with a small example:

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3]])
print("a row vector:\n", a)
b = a.transpose()
print("b column vector:\n", b)

a row vector:
 [[1 2 3]]
b column vector:
 [[1]
 [2]
 [3]]


You will see a vector contains three elements, *a* is called row vector, *b* is called column vector. The only different between *a* and *b* is the position of the elements.  

In linear algebra, the concept of a vector has been abstracted, we are no longer limited to directions, we are transformed to think about more general states, and as you can see, a representation in the shape of $a(a1,a2,...,an)$ is a vector.

#### *2.2 Matrix*

Well down, We got vectors!  

The Next step, We combine the vectors, arranging them layer by layer like spreading jam, and in this way we get the most basic, and most important, element of quantum computing------the matrix

You may have a little bit confused. How to describe a matrix?  

Nice question! For example, the matrix below, which is c, has three blocks; each block has three numbers, so we call c the $3 \times 3$ matrix. The first three represent how many rows in this matrix, and the second three represent haw many columns in this matrix.  

So when you meet a matrix X, which is $m \times n$, means X has m rows and n columns.

In [3]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("c the matrix:\n", c)

c the matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


#### *2.3 Matrix Computing Methods*

All right, we've made good friends with vectors and matrices, and the next thing we need to know is how these friends of ours do their calculations.

##### *2.3.1 Matrix multiplication*

In this section, we will meet some mathematics formulas, but don't worry, they won't hurt you. You got me. The first thing we need to understand is that how two matrixes do multiplication? You may say just like the real number. This is a good answer, but not correct. Indeed, some parts of multiplication can be described like real number, but not all of them. We use the formula below to calculate the multiplication of matrixes:  

Prerequisite: A is a matrix which is $n \times m$, B is another matrix which is $m \times p$  

The formula: $$C_i_j = a_i_1b_1_j + a_i_2b_2_j + ... + a_i_nb_n_j$$  
$$= \sum_{k = 1}^{n}a_i_kb_b_j$$  

We have to admit one thing if only the number of the first matrix's columns equals the number of the second matrix's rows, then these two matrixes can multiply.


In [4]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
e = np.array([[10,11,12],[13,14,15],[16,17,18]])
print(np.matmul(d, e))

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


##### *2.3.2 Inner Product*
  
Inner product can be treated as a special matrix multiplication.  

For two vectors in Hilbert space $|a>$ and $|b>$, $<a|b>$this means that their inner product. And $<a|$ is defined as $|a>$'s conjugate transpose. This can also be noted as $|a>^†$.  

The notation $†$, called "dagger", means conjugate transpose.  

So you may have another question. What is conjugate transpose? Conjugate transpose means you turn a row vector first into a column vector(vice versa) then take the conjugate of the data inside.  

P.S: Conjugate: When we take the conjugate of $a+bi$ it will become $a-bi$  

$$\begin{aligned}<a|b> = (a_1, a_2, a_3,..., a_n)^†\times(b_1, b_2, b_3,..., b_n) = a_1^*b_1 + a_2^*b_2 + ... + a_n^*b_n\end{aligned}$$

In [5]:
base = np.arange(3)
f = base - 1j * base
g = base - 2j * base
print("vector f: \n", f)
print("vector g: \n", g)
print("The conjugate vector f: \n", np.conjugate(f))

print("<f|g>: \n", np.inner(np.conjugate(f), g))

vector f: 
 [0.+0.j 1.-1.j 2.-2.j]
vector g: 
 [0.+0.j 1.-2.j 2.-4.j]
The conjugate vector f: 
 [0.-0.j 1.+1.j 2.+2.j]
<f|g>: 
 (15-5j)


##### *2.3.3 Outer Product*

That's right! We got inner product, so we must have outer product.  

$|a><b|$represent outer product of two vectors in Hilbert space.

$$\begin{aligned}|a><b| = (a_1, a_2, a_3,..., a_n)\times(b_1, b_2, b_3,..., b_n)^† = a_1b_1^* + a_2b_2^* + a_3b_3^* + ... + a_nb_n^*\end{aligned}$$

In [6]:
print("|f><g|: \n", np.outer(f, np.conjugate(g)))

|f><g|: 
 [[ 0.+0.j  0.+0.j  0.+0.j]
 [ 0.-0.j  3.+1.j  6.+2.j]
 [ 0.-0.j  6.+2.j 12.+4.j]]


##### *2.3.4 Tensor Product*

Finally! We meet the most-most-most important calculation method ------ the tensor product.  

We first talk about the vector:

$|a>\otimes|b>$denotes the tensor product of two vectors in Hilbert space. So we can get:
$$\begin{aligned}|a>\otimes|b> = (a_1b_1, a_1b_2, a_2b_1, a_2b_2)^T\end{aligned}$$ T means turn row vector to column vector(vice versa).

In [7]:
np.kron(f, g)
print("|f> tensor |g>: \n", np.kron(f, g))

|f> tensor |g>: 
 [ 0. +0.j  0. +0.j  0. +0.j  0. +0.j -1. -3.j -2. -6.j  0. +0.j -2. -6.j
 -4.-12.j]


Then the matrix A and B:

$$A\otimes B = $$
$$\left(\begin{array}{ccc}
a_1_1B & \ldots  &a_1_nB \\\\
\vdots & \ddots & \vdots \\\\
a_n_1B & \ldots & a_n_nB
\end{array}\right)$$

In [8]:
np.kron(np.eye(2), np.ones((2, 2)))
print("A tensor B: \n", np.kron(np.eye(2), np.ones((2, 2))))

A tensor B: 
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]
